POST http://localhost:5000/hotels/update/643a50b4dc2e7ca880ba8f9a
Content-Type: application/json

{
  "name":"Hotel Mlem",
  "typeHotel":"Hotel",
  "city":"berlin",
  "address":"124a5d5ad5asda578",
  "distance":"500",
  "desc":"hotel desc",
  "rating":5,
  "featured":true,
  "rooms":["likee"],
  "cheapestPrice":1000
}

###

PUT http://localhost:5000/hotels/update/643a50b4dc2e7ca880ba8f9a
Content-Type: application/json

{
  "name":"Hotel Lover"
}

###
DELETE http://localhost:5000/hotels/delete/643a50b4dc2e7ca880ba8f9a

###
GET http://localhost:5000/hotels

